# Generated by Django 2.2.19 on 2021-03-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateField(blank=True, help_text='Formato DD/MM/AAAA', null=True, verbose_name='Data de Nascimento'),
        ),
    ]
