# Generated by Django 2.2.19 on 2021-03-26 11:41

import aplic.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0002_aluno_data_nascimento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nova',
        ),
        migrations.AddField(
            model_name='aluno',
            name='foto',
            field=stdimage.models.StdImageField(null=True, upload_to=aplic.models.get_file_path, verbose_name='Imagem'),
        ),
        migrations.AddField(
            model_name='professor',
            name='foto',
            field=stdimage.models.StdImageField(null=True, upload_to=aplic.models.get_file_path, verbose_name='Imagem'),
        ),
    ]
