# Generated by Django 2.2.19 on 2021-03-26 11:51

import aplic.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0003_auto_20210326_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='foto',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=aplic.models.get_file_path, verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='foto',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=aplic.models.get_file_path, verbose_name='Foto'),
        ),
    ]
