# Generated by Django 2.2.19 on 2021-04-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0004_auto_20210326_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='linkedin',
            field=models.CharField(blank=True, max_length=200, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='twitter',
            field=models.CharField(blank=True, max_length=200, verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='professor',
            name='curriculo',
            field=models.TextField(blank=True, max_length=500, verbose_name='Currículo'),
        ),
        migrations.AddField(
            model_name='professor',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='professor',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='professor',
            name='linkedin',
            field=models.CharField(blank=True, max_length=200, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='professor',
            name='twitter',
            field=models.CharField(blank=True, max_length=200, verbose_name='Twitter'),
        ),
    ]
