# Generated by Django 2.2.19 on 2021-04-08 16:26

import aplic.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0005_auto_20210408_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='imagem',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=aplic.models.get_file_path, verbose_name='Foto'),
        ),
    ]
