# Generated by Django 2.2.19 on 2021-06-04 12:33

import aplic.models
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0006_curso_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='imagem',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=aplic.models.get_file_path, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='aplic.Curso'),
        ),
    ]
